language: cpp
compiler:
  - gcc
# - clang

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libboost-all-dev autoconf-archive

before_script:
  - set -e
  - echo $LANG
  - echo $LC_ALL
  - g++ --version
  - aclocal --version
  - autoconf --version
  - automake --version
  - make --version

script:
  - ./bootstrap
  - ./configure
  - make

after_script:
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ./test_eterm
